"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";

export default function AdminPage() {
    const router = useRouter();

    useEffect(() => {
        // Redirect to the static admin panel generated by Tina
        window.location.href = "/admin/index.html";
    }, []);

    return (
        <div className="min-h-screen flex items-center justify-center bg-stone-900 text-white">
            <div className="text-center">
                <div className="w-16 h-16 border-4 border-amber-200 border-t-amber-700 rounded-full animate-spin mx-auto mb-4"></div>
                <p className="text-stone-400 font-serif text-xl">Loading Admin Panel...</p>
            </div>
        </div>
    );
}
